export const Config = {
  FE: [
    "Html 5",
    "CSS 3",
    "JavaScript",
    "TypeScript",
    "Sass",
    "Bootstrap",
    "Wordpress",
    "Axios / Fetch",
    "Jest",
    "Webpack",
    "Bootstrap",
    "JQuery",
    "React",
    "AngularJs",
    "Cypress",
    "AWS Amplify",
    "Jwt",
    "Redux",
    "Redux Saga",
    "Zustand",
    "Valtio",
    "Jotai",
    "Styled-Components",
    "Emotion",
    "Material-UI",
    "React-Query",
    "Testing Library",
    "React Hook Form",
    "Framer Motion",
  ],
  BE: [
    "SSL",
    "MongoDB",
    "Postgres SQL",
    "Jwt",
    "Swagger",
    "SQL",
    "NodeJs",
    "Express",
    "Prisma 2",
    "Mongoose",
    "Helmet",
    "Cors",
    "Winston",
    "Morgan",
    "C#",
    "Entity Framework",
    ".Net",
    "Linq",
    "Nunit",
    "Visual Studio",
    "PHP",
    "Laravel",
    "Doctrine",
    "Wordpress",
  ],
  DO: [
    "Nginx",
    "Pm2",
    "SSH",
    "Bash",
    "Ubuntu Server",
    "Docker",
    "Bitbucket Pipelines",
    "AWS S3",
    "Aws Cognito",
    "Digital Ocean",
  ],
};
